version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm test || echo "No tests defined"
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - '**/*'
  base-directory: .
